# Topics of interest and minimum acceptable frequencies (Hz) of their respective messages

/gps/fix:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame_id: gps
/gps/gps:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame_id: gps
/gps/imu:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: imu_link
/ibeo_interface_node/ibeo/lidar/dynamic:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: 25
    frame: base_link
/ibeo_interface_node/ibeo/lidar/static:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: 25
    frame: base_link
/ibeo_interface_node/ibeo/objects:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: base_link
/ibeo_interface_node/ibeo/odometry:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 25
    frame: base_link
/ibeo_interface_node/ibeo/gnss:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: base_link
/ibeo_interface_node/xsens/IMU:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 81
    frame: base_link
/imu/data_raw:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 125
    frame: imu_link
/novatel/oem7/bestpos:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: gps
/novatel/oem7/inspva:
    required_in_rosbag: no
    required_frequency_check: no
    rate: xx
    frame: gps
/novatel/oem7/odom:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: base_link
/novatel/oem7/time:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: gps
/ouster/imu_packets:
    required_in_rosbag: no
    required_frequency_check: no
    rate: 100
    frame: xx
/ouster/lidar_packets:
    required_in_rosbag: no
    required_frequency_check: no
    rate: 644
    frame: xx
/ouster/imu:
    required_in_rosbag: no
    required_frequency_check: yes
    rate: 100
    frame: os_sensor
/ouster/points:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 10
    frame: os_sensor
/ouster/metadata:
    required_in_rosbag: no
    required_frequency_check: no
    rate: xx
    frame: xx
#verify the transformations  
/tf_static:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: xx 
/tf:
    required_in_rosbag: yes
    required_frequency_check: no
    rate: xx
    frame: xx
# image data
/sekonix_camera/port_a_cam_0/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
    frame: port_a_cam_0 
/sekonix_camera/port_a_cam_1/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_b_cam_0/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_b_cam_1/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_c_cam_0/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_c_cam_1/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_d_cam_0/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_d_cam_1/camera_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_a_cam_0/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_a_cam_1/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_b_cam_0/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_b_cam_1/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_c_cam_0/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_c_cam_1/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_d_cam_0/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
/sekonix_camera/port_d_cam_1/frame_info:
    required_in_rosbag: yes
    required_frequency_check: yes
    rate: 30.0
